-- MySQL Script generated by MySQL Workbench
-- ‫چارشنبه ۱۵ آوریل ۲۰، ۰۲:۱۹:۰۱‬
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MikaeelGhr$Zaban
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MikaeelGhr$Zaban
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MikaeelGhr$Zaban` DEFAULT CHARACTER SET utf8 ;
USE `MikaeelGhr$Zaban` ;

-- -----------------------------------------------------
-- Table `MikaeelGhr$Zaban`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MikaeelGhr$Zaban`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MikaeelGhr$Zaban`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MikaeelGhr$Zaban`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MikaeelGhr$Zaban`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MikaeelGhr$Zaban`.`lessons` (
  `number` INT NOT NULL,
  `books_id` INT NOT NULL,
  `books_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`number`, `books_id`, `books_name`),
  INDEX `fk_lessons_books_idx` (`books_id` ASC, `books_name` ASC),
  CONSTRAINT `fk_lessons_books`
    FOREIGN KEY (`books_id` , `books_name`)
    REFERENCES `MikaeelGhr$Zaban`.`books` (`id` , `name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MikaeelGhr$Zaban`.`readings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MikaeelGhr$Zaban`.`readings` (
  `number` INT NOT NULL,
  `lessons_number` INT NOT NULL,
  `lessons_books_id` INT NOT NULL,
  `lessons_books_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`number`, `lessons_number`, `lessons_books_id`, `lessons_books_name`),
  INDEX `fk_readings_lessons1_idx` (`lessons_number` ASC, `lessons_books_id` ASC, `lessons_books_name` ASC),
  CONSTRAINT `fk_readings_lessons1`
    FOREIGN KEY (`lessons_number` , `lessons_books_id` , `lessons_books_name`)
    REFERENCES `MikaeelGhr$Zaban`.`lessons` (`number` , `books_id` , `books_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MikaeelGhr$Zaban`.`words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MikaeelGhr$Zaban`.`words` (
  `name` VARCHAR(40) NOT NULL,
  `readings_number` INT NOT NULL,
  `readings_lessons_number` INT NOT NULL,
  `readings_lessons_books_id` INT NOT NULL,
  `readings_lessons_books_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`, `readings_number`, `readings_lessons_number`, `readings_lessons_books_id`, `readings_lessons_books_name`),
  INDEX `fk_words_readings1_idx` (`readings_number` ASC, `readings_lessons_number` ASC, `readings_lessons_books_id` ASC, `readings_lessons_books_name` ASC),
  CONSTRAINT `fk_words_readings1`
    FOREIGN KEY (`readings_number` , `readings_lessons_number` , `readings_lessons_books_id` , `readings_lessons_books_name`)
    REFERENCES `MikaeelGhr$Zaban`.`readings` (`number` , `lessons_number` , `lessons_books_id` , `lessons_books_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MikaeelGhr$Zaban`.`synonyms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MikaeelGhr$Zaban`.`synonyms` (
  `words_name` VARCHAR(40) NOT NULL,
  `words_name1` VARCHAR(40) NOT NULL,
  INDEX `fk_synonyms_words1_idx` (`words_name` ASC),
  INDEX `fk_synonyms_words2_idx` (`words_name1` ASC),
  CONSTRAINT `fk_synonyms_words1`
    FOREIGN KEY (`words_name`)
    REFERENCES `MikaeelGhr$Zaban`.`words` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_synonyms_words2`
    FOREIGN KEY (`words_name1`)
    REFERENCES `MikaeelGhr$Zaban`.`words` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `MikaeelGhr$Zaban` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `MikaeelGhr$Zaban`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
